roessolver: Roes\ Riemann\ Solver/roes_riemann_solver.c
	cd Roes\ Riemann\ Solver/ && \
	gcc roes_riemann_solver.c -o roes_riemann_solver.exec && \
	./roes_riemann_solver.exec && \
	python rho_plot.py && \
	rm roes_riemann_solver.exec *.txt
