athena: Athena/kelvin.param Athena/src/prob/kelvin.c
	cd Athena && \
	#./configure  --with-problem=kelvin  --with-gas=hydro  --with-eos=adiabatic  --with-flux=roe && \
	#make all && \
	./bin/Athena  -i kelvin.param
