macheps: Machine\ Epsilon/macheps.c
	cd Machine\ Epsilon && \
	gcc macheps.c -o macheps.exec && \
	./macheps.exec && \
	rm macheps.exec

floatrep: Floating\ Point\ Representation/floatrep.c
	cd Floating\ Point\ Representation && \
	gcc floatrep.c -o floatrep.exec && \
	./floatrep.exec && \
	rm floatrep.exec

summing: Summing\ Numbers/summing.c
	cd Summing\ Numbers && \
	gcc summing.c -lgmp -o summing.exec && \
	./summing.exec && \
	rm summing.exec

test: Test\ Code\ Environment/test.c
	cd Test\ Code\ Environment && \
	gcc test.c -o test.exec && \
	./test.exec && \
	rm test.exec
